### ISSUE TITLE
Add pixel grid

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#10]
Add a pixel grid that can optionally be displayed starting at a zoom threshold of 400%

**Tasks:**
- [x] Add startup setting for whether grid is enabled on startup
- [x] Add toolbar toggle icon for grid
  - [x] Tool tip
- [x] Toggle shortcut **[Ctrl + G]**
- [x] Info page blurb on "More" page
