### ISSUE TITLE
Prepare from-source compilation with instructions

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#104]
### Description
Once released, Stipple Effect will cost money, but will be able to be compiled from source. To facilitate this, I must distribute the dependencies (besides ANTLR) as GitHub releases and provide instructions on the program's primary landing pages.

### References
* [Paint.NET releases](https://github.com/paintdotnet/release/releases)

### Tasks
- [x] Animation Encoder
  - [x] Add a README
  - [x] Make `animation-encoder` repo public
  - [x] Publish JAR as a single unversioned release called "auxiliary"
- [x] Delta Time
  - [x] Add README
  - [x] Publish JAR as a single unversioned release called "auxiliary"
- [x] Instructions
  - [x] Include ANTLR version
  - [x] Add to store page and to GitHub README
