### ISSUE TITLE
Separate selection from color action scope

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#107]
### Description
Turn `ignore_selection` into a flag like `include_disabled_layers` and remove it from `DialogVals.Scope`.

### Tasks
* [x] Change color action implementations
* Layout changes
  * [x] Update `DialogAssembly.makeCommonColorOperationElements` with new flag
  * Shift index of following element down by one in each color operation dialog
    * [x] Palettize
    * [x] Extract to palette
    * [x] HSV shift
    * [x] Color script
* Update API
  * [x] Update node classes
  * [x] Update docs
  * [x] Document changes in API changes
