### ISSUE TITLE
Add Timeline UI panel option

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#117]
### Description
The Timeline UI panel combines the Layers and Frames panels into one.

* There should be an option on the panel manager to toggle between "Timeline" mode and "Classic" mode. 
* The Timeline should sit directly above the bottom bar. Breadth TBD. 
* Frame and layer buttons should be draggable to enable easier resorting. This will require custom menu elements. 
* Layer-frames should be renamed to "cels"; cel buttons should be selectable as part of a single rectangular selection. This selection can be copied and pasted iff there are enough layers below the currently selected cel layer to support the paste operation. The project should be appended with frames as necessary to support the paste operation.

### Tasks
- [x] Design layout of Timeline panel
- [ ] Make Timeline and Layers/Frames mutually exclusive
  - [ ] Add toggle setting in `DialogVals`
  - [ ] Update panel manager with setting and a thinking element to show the classic or timeline inclusion options based on setting value
- [ ] Update all of the layout calculation logic in `Layout`
  - [x] `Colors` panel takes up the space allotted to `Layers` and combines its slider and palette tabs into one in timeline mode
  - [x] `Projects` panel takes up the full breadth of the window and is always collapsible in timeline mode
- [x] Implement draggable buttons for layers and frames
- [x] Implement selectable buttons for cels
  - [x] Copy and paste with unique `DataFlavor`
