### ISSUE TITLE
Redesign layer-specific buttons

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#12]
**Tasks:**
- [x] Integrate _isolate layer_ behaviour into visibility button and remove independent _isolate layer_ button
  - [x] Extend toggle button to allow for unique modified input behaviours (e.g. _Shift + Click_ or _Right Click_)
  - [x] Isolate layer instead of toggling visibility if button is shift-clicked
- [x] Move onion skinning to after layer-frame locking
- [x] Lock onion skinning toggle on disabled if layer is frame-locked
- [x] ~~Add other layer properties to layer settings dialog~~
- [x] Extend number of characters of the layer name that can be printed on the button before the cutoff thanks to the additional icon button worth of space that removing _isolate layer_ button will make available
