### ISSUE TITLE
Redesign "Colors" panel

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#125]
### Description
Redesign the colors panel to feature multiple color selection modes and to combine the color selection and palette UI onto a single panel.

### Tasks
* Color selection methodologies
  * RGB-HSV-A sliders
  * [x] Color wheel + opacity slider
  * [x] Saturation-value chart + hue and opacity sliders
* [x] Move palettes under color selection and get rid of *Ctrl + Shift + C* shortcut and button
