### ISSUE TITLE
Overhaul and extend palette sub-menu of color selection menu

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#13]
**Tasks:**
- [x] Add buttons:
  - [x] Remove palette button
  - [x] Create new, blank palette button
  - [x] Move selected color left/right in palette buttons (precondition is selected color is in palette)
  - [x] Palette settings (launches dialog akin to layer settings button)
    - [x] Make name editable
    - [x] Immutable palettes cannot be edited (button precondition is mutability)
- [x] Split palette buttons along lines of functionality into two rows - can still be created with calls to icon button populator; offset second row segment position (`Coord2D`) by `0, Layout.BUTTON_INC`
- [x] Extend palette color button so that shift-clicking buttons **excludes** them from shading and palettization processes
  - [x] Add `final Map<Color, Boolean> inclusionMap` field to `Palette` class - propagate changes to `colorSequence` contents to `inclusionMap`
  - [x] Add exclusion overlay sprite and render **above** potential primary/secondary color selection overlay on palette color button
- [x] Assign and implement shortcuts
- [x] Write and check tool tips and info page blurbs
