### ISSUE TITLE
Add option to embed preview window in the main program window

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#134]
### Description
It should be possible to have the preview window be either a separate window, or embedded in the main program window. This should be determined by a Visual Setting.

### Tasks
* [x] Generalize class `PreviewWindow` so that it works as a `Menu` or `MenuElement` or as a self-contained `ProgramContext` for a separate window
* [x] Ensure that menu elements behind embedded preview window are not mouse-interactable
* [x] Resolve keyboard shortcuts for preview window actions that have main window equivalents (e.g. cycling playback mode, play/pause, shift playback FPS)
