### ISSUE TITLE
Add shade brush

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#14]
Add a shade brush tool (dedicated tool separate from _brush_ tool) that replaces the previous color that was drawn over with the adjacent color in the palette's present color order iff the color that was drawn over was in the palette and has an adjacent color in the relevant direction. _Left click_ shifts the replacement color to the left in the palette; _right click_ to the right.

**Preconditions for implementation:**
- [x] #13 
- [x] #15 

**Tasks:**
- [x] Tool button
  - [x] Tool icon sprite
  - [x] Tool tip
- [x] Tool assignment shortcut [ **D** ]
- [x] `class ShadeBrush` and tool behaviour
- [x] Info menu blurb (Tools page)
