### ISSUE TITLE
Onion skin extension

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#142]
### New onion skin data structure

* `enum SkinType`
  * `SIMPLE` - like existing implementation
  * `OUTLINE` - capture pixels with transparent adjacent pixels
  * `TINTED` - contents of the cel tinted in a particular hue
* `double hue` - `0.0` to `1.0`; only applies to `OUTLINE` and `TINTED`
* Frame counts
  * `int lookForward` - `0` to `6`?
  * `int lookBack` - `0` to `6`?
* `double fadeFactor` - `0.1` to `1.0`?; opacity multiplier per frame removed from current frame index

### TODO

* [x] Implement data structure in `SELayer`
  * [x] Resolve whether to treat onion skin settings changes as state changes, as onion settings will be saved to `.stip` files per layer
* [x] Update `ParserSerializer` to read and write onion skin settings per layer
  * [x] Ensure a default state if parser cannot read onion skin settings
  * [x] Increment file standard
* [x] Change onion skin layer button from a cycle to a simple toggle

### Considerations

This could be very computationally expensive. Try to render onion skins once per `SELayer` instantiation if the layer is not linked (as I believe I am doing now), and find as inexpensive a solution as possible to process an onion skin with its fade factor in `ProjectState.draw()`.

In that spirit, consider a pre-processing step that...
1. Calculates the smallest possible rectangular area in a cel with non-transparent pixel content
2. Uses that rectangular area to render the onion skin content (`GameImage`)
3. Stores the (x, y) position of that rectangular area in the cel, along with the onion skin content, in a separate data structure

### Stretch goals

* [ ] #145
