### ISSUE TITLE
Alternative brush shapes

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#143]
### In addition to a circular brush, implement...
* [x] square brush
* [x] linear brush
  * [x] rotation angle

These brushes will still utilize the breadth property.

### Tools
**Not all `ToolWithBreadth` are affected!!**
* Brush
* Shade brush
* Script brush
* Eraser
* Gradient tool

### TODO
* [x] Implement alternative brush shapes in a polymorphic way
* [x] Consider a setting that propagates breadth tool updates to all other breadth tools
* [x] Add new properties to tool options bar in a polymorphic way
  * [x] Shorten excessively wordy tool options to make space
    * [x] Combination mode bias
    * [x] Script brush upload status
    * [x] Consider separating gradient tool options under a dropdown
      * Brush settings
        * Breadth
        * Brush shape (+ angle if applicable)
        * Dithered?
      * Gradient settings
        * Shape
        * Bounded
        * Mask? + (+ contiguous? and tolerance if applicable)
