### ISSUE TITLE
Add CLI for testing, debugging, running scripts

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#149]
### Requires
* jbunke/delta-time#14

### Overview

Create a CLI tool for Stipple Effect to test, debug and run scripts.

### Tasks
* [ ] Decouple the scripting system from the program instance (`StippleEffect.get()`)
* [ ] Build in safeguards to prevent CLI from attempting to launch program
* [ ] Build CLI around the DeltaScript CLI if scope of SE CLI extends beyond scripting
  * Potential applications beyond scripting:
    * Viewing and setting program settings
