### ISSUE TITLE
Add line tool

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#16]
Add a line tool. Click and drag to draw a line, unclick to place it. Holding _Shift_ will snap line to the nearest 15-degree angle. Holding _Ctrl_ will make the line a gradient ranging from the primary to the secondary color.

**Preconditions for implementation:**
- [x] #15 
- [x] #17 

**Tasks:**
- [x] Tool button
  - [x] Tool icon sprite
  - [x] Tool tip
- [x] Tool assignment shortcut [ **L** ]
- [x] `class Line` and tool behaviour
  - [x] Override `hasToolContentPreview()` and `getToolContentPreview(final ProjectState state)`
- [x] Info menu blurb
