### ISSUE TITLE
Add `light` type

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#163]
Add a single `light` type to the scripting API that can be used to define light objects to be passed as arguments to `$Graphics` functions.

### Tasks

* Implementation
  * [ ] Type node class
  * [ ] Internal representation class
  * Constructor nodes
    * [ ] `$Graphics.dir_light(float luminosity, color light_color, ...) -> light`
    * [ ] `$Graphics.point_light(float luminosity, color light_color, ...) -> light`
  * Accessor expression nodes
    * [ ] `L.is_point() -> bool`
    * [ ] `L.get_luminosity() -> float`
    * [ ] `L.get_color() -> color`
    * [ ] `L.get_direction() -> float[]`
    * [ ] `L.get_position() -> int[]`
    * [ ] `L.get_radius() -> float`
    * [ ] `L.get_z() -> float`
  * Mutator statement nodes
    * [ ] `L.set_luminosity(float);`
    * [ ] `L.set_color(color);`
    * [ ] `L.set_direction(float[]);`
    * [ ] `L.set_position(int[]);`
    * [ ] `L.set_radius(float);`
    * [ ] `L.set_z(float);`
* Update API
  * [ ] `light` type page
  * [ ] Updated function signatures in `$Graphics`
