### ISSUE TITLE
Add a `GameImage getToolContentsPreview(final ProjectState state)` function to `Tool`

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#17]
This will have the same bounds as the canvas when non-trivial and will be drawn after the selection contents on the editing layer in `ProjectState.draw()`.

**Tasks:**
- [ ] define default behaviour in Tool as `return GameImage.dummy();`
- [ ] Override in `Line` and `GradientBrush` and future tools that necessitate content previews
- [ ] Add parameter to `ProjectState.draw()` that accounts for whether to draw tool content preview
