### ISSUE TITLE
Add gradient brush tool

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#18]
Add a gradient brush tool that remembers the pixels it has painted over separately for every target pixel change. That way, ...

**Preconditions for implementation:**
- [x] #15 
- [x] #17 

**Tasks:**
- [x] Tool button
  - [x] Tool icon sprite
  - [x] Tool tip
- [x] Tool assignment shortcut [ **G** ]
- [x] `class GradientBrush` and tool behaviour
  - [x] Override `hasToolContentPreview()` and `getToolContentPreview(final ProjectState state)`
- [x] Info menu blurb
