### ISSUE TITLE
Optimize STIP file by making saving static layers as their single propagated frame instead of an array of N identical frame representations

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#21]
**Tasks:**
- [ ] Check if `SELayer` needs refactor to make static layer loadable from a single deserialized `GameImage`
- [ ] Change behaviour in `ParserSerializer`
- [ ] Increment STIP file standard to 1.1 as 1.0 should still be compatible
