### ISSUE TITLE
Change checkerboard size settings

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#23]
Change the single checkerboard size setting into two - one for X and one for Y - making each dimension independent

**Tasks:**
- [x] Change setter menu element(s) from slider(s) to text boxes with suffix "px"
- [x] Range of valid values is to be 1 - 256 inclusive
  - [x] Consider adding info label on the visual settings menu page that indicates the valid range
- [x] Update `SEContext.redrawCheckerboard` to account for changes
- [x] Update `class Settings`
