### ISSUE TITLE
Snapping behaviour for move selection

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#25]
Holding Shift while moving the selection with either mover tool (move selection or pick up selection), whether with the arrow keys or click and drag, should snap to multiples of the selection's dimensions. 

With arrow keys: instead of incrementing position by +/- 1 on either x or y, incrment by the selection's relevant dimension (width or height)
With click and drag: snap delta position to nearest multiple of selection's dimensions

**Tasks:**
- [x] Update snap check in `MoverTool`
- [x] Update arrow key behaviour
- [x] Update click and drag behaviour
