### ISSUE TITLE
Add Polygon Select tool

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#26]
Add a polygon select tool that uses rudimentary pixel raycasting to determine whether pixels in rectangular bound area are in- or outside the defined polygon.

**Tasks:**
- [x] Tool button
  - [x] Tool icon sprite
  - [x] Tool tip
- [x] Tool assignment shortcut [ **Y** ]
- [x] `class PolygonSelect` and tool behaviour
  - [x] Override `hasToolContentPreview()` and `getToolContentPreview(final ProjectState state)`
- [x] Info menu blurb
- [x] Series of cursors
  - [x] Draw cursor sprites
  - [x] Update `SECursor`
