### ISSUE TITLE
Add text tool

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#33]
**Prerequisites:**
- [x] #32 

**Tasks:**
- [x] Reassign *brush select* tool to hotkey [ **V** ]
- [x] Tool button
  - [x] Letter 'T' tool icon sprite
  - [x] Tool tip
- [x] Tool assignment hotkey [ **T** ]
- [x] `class TextTool` and tool behaviour
  - [x] Override `hasToolContentPreview()` and `getToolContentPreview(final ProjectState state)`
- [x] Info menu blurb
- [x] Series of cursors
  - [x] Draw cursor sprites
    - [x] I-beam
    - [x] Caret (no flash)
  - [x] Update `SECursor`
- [x] Implement tool options bar behaviour
  - [x] Font selection from custom drop down which previews text in font
  - [x] Upload font button with add font dialog
  - [x] Scale factor controls (integer from 1-10)
