### ISSUE TITLE
Add frame stitching and splitting behaviours

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#37]
### Description
This should enable easy assembly and disassembly of sprite sheets. If a project has a single frame, it can be split. If a project has multiple frames, it can be stitched together.

### Approach
For `stitch` and `split` functions:
- Build back from `final ProjectState result` definition; this will be a `getState()` call appended with mutator-returners

### Tasks
- Split dialog
  - [x] Mockup
  - [x] UI assembly
  - [x] Condition validation
- Stitch dialog
  - [x] Mockup
  - [x] UI assembly
  - [x] Condition validation
- `split` and `stitch` functions
  - [x] Preserve layer data
    - [x] Pixel content
    - [x] Visibility
    - [x] Opacity
    - [x] Onion skin mode
    - [x] For `stitch`, auto-lock all layers
    - [x] For `split`, auto-unlock all layers
