### ISSUE TITLE
Overhaul preview window

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#39]
**Tasks:**
- [x] Add border to canvas preview to satisfy window minimum size requirement
- [x] Add zoom controls to preview window
- [x] Separate playback from main window and add playback controls on preview window
