### ISSUE TITLE
Use Unicode Private Use Area in BMP (U+E000 to U+F8FF) to extend Delta Time font character set for composed Yoruba letters (subdot + tonal mark)

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#40]
**Description:**
Use Unicode [Private Use Area](https://en.wikipedia.org/wiki/Private_Use_Areas) in [BMP](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane) (U+E000 to U+F8FF) to extend [Delta Time](https://github.com/jbunke/delta-time) font character set for *composed Yoruba letters* (subdot + tonal mark)

**Tasks:**
- Yoruba letters to add
  - [x] ọ+ò
  - [x] ọ+ó
  - [x] ẹ+è
  - [x] ẹ+é
  - [x] ń
  - [x] ǹ
- [x] Assign further letters
- [x] Research [escaped Unicode character literals](https://stackoverflow.com/questions/21522770/unicode-escape-syntax-in-java) in Java (e.g. `'\uE000'`)
- [x] Think about how to parse these from plain text via *Delta Time* for the sake of *Readler*
