### ISSUE TITLE
Extend `GradientTool` behaviour again

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#41]
### Description
Extend `class GradientTool` to...
- Have an additional scope mode where only the pixels of the same colour as the initial anchor pixel are replaced
- Have a spiral shape

### Prerequisites
- #43 

### Tasks
- Same colour scope
  - [x] Convert field `boolean wholeCanvas` to an `enum Scope` with literals `WHOLE_CANVAS, START_TO_END, WHOLE_CANVAS_MASKED, START_TO_END_MASKED`
  - [x] Add same colour behaviour to `...MASKED` enum constants
  - [x] Extend with tolerance
- Spiral
  - [x] Use `Geometry.calculateAngleInRad` to get started with the `getC` function for new enum constant `SPIRAL` in `enum Shape`
