### ISSUE TITLE
Add second snap mode to `MoverTool` implementations for pixel grid snapping

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#42]
### Description
Add a second snap mode to the `MoverTool` implementations (`MoveSelection` and `PickUpSelection`) where the *top left* of the selection area is snapped to the *top left* of the pixel grid cell that is occupied. This will exist alongside the existing snap mode, which moves the selection area by the nearest multiple of its own dimensions.

### Tasks
- [x] Add boolean field in `MoverTool` to toggle between potential snap modes
- [x] Assign a toggle key - tentatively **[ Ctrl ]**
- [x] Implement pixel grid snapping behaviour
  - [x] Ensure pixel grid checks are passed before executing snap
    - Reference `BoxSelect` snap implementation to ensure consistency
- [x] Update tool blurbs to account for extended behaviour
