### ISSUE TITLE
Generalize dither percentage option in `ToolThatDraws` to "tendency" and apply to all color modes

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#45]
### Description
Reimplement field `DitherStage ditherStage` in `ToolThatDraws` as a field `double tendency` that ranges from `0d` to `1d`. This tendency describes how much each color sampling mode (`DITHER`, `BLEND` and `NOISE`) will tend towards the primary color vs the secondary color.

### Tasks
- [x] Change the tool options bar implementation, implementing the slider as a 0 - 100 scale and the value formatter as multiplying `tendency` by 100 and casting it to `int` before describing it as a percentage
- [x] Color sampling mode implementations
  - [x] `DITHER`: get the dither stage from the nearest fraction just like how `GradientTool` does it
  - [x] `BLEND`
    - Multiply primary channel by tendency and add to secondary channel multiplied by complement of tendency
    - Only cast to `int` after addition
    - Something like `(int) ((primary.getRed() * tendency) + (secondary.getRed() * (1d - tendency)))`
  - [x] `NOISE`: Figure out if a tendency application for noise mode makes sense and what the maths would entail
