### ISSUE TITLE
Add HSV shifting and brightness/contrast adjustment

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#46]
### Description
Add dialogs for HSV shifting and brightness/contrast adjustment for a variety of scopes.

### Tasks
- [x] Add buttons and shortcuts to colors menu to open dialogs
  - [x] HSV shifting
  - [ ] Brightness/contrast
- [ ] Research maths
- [x] In-dialog previews
- [x] Same scopes as palette operations:
  - [x] Layer-frame
  - [x] Layer
  - [x] Frame
  - [x] Selection
  - [x] Project
- [x] Reference Brandon James Greer's [hue shifting video](https://www.youtube.com/watch?v=PNtMAxYaGyg) to for intuitive relationships between hue, sat., and value (presets)
