### ISSUE TITLE
Change internal versioning system

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#49]
### Description
Change Stipple Effect's internal versioning system to match what Delta Time does.

### Tasks
- [x] Use Delta Time's `Version` class
- [x] Separate devbuild status to outside of version number
- [x] Add incrementation system
