### ISSUE TITLE
Enclose preview image menu element in a custom implementation of `BidirectionalScrollBox`

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#58]
### Description
Enclose the preview image menu element in a custom implementation of `AbstractBidirectionalScrollBox` from Delta Time.

### Tasks
- [x] Change `ScrollBox` in Delta Time to pass a blank `GameImage` of same bounds as `canvas` to `render()` function of the elements enclosed in its box. Draw the section of this `GameImage` bounded by the `bounds` of the `ScrollBox` to `canvas` at the `getRenderPosition()` of the `ScrollBox`
- [x] Bounds of bidirectional scroll box implementation should be `MAX_CANVAS_W + SLIDER_OFF_DIM` x `MAX_CANVAS_H + SLIDER_OFF_DIM`
- [x] Ensure scroll behaves as expected:
  - [x] Change zoom level when scroll box has no sliders
  - [x] Scroll vertically when scroll box has vertical slider or both sliders
  - [x] Scroll horizontally iff scroll box only has horizontal slider
