### ISSUE TITLE
Settle on a license and distribution model

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#59]
### Description
Settle on a license and a distribution strategy for Stipple Effect.

### Tasks
- [x] Pricing - launch at $3.00 (USD)
- [x] License
  - [x] Add license to repo
  - [x] Add license to Itch.io metadata
- [x] Open source model
  - [x] Like Aseprite?
  - [x] Stop including program builds/binaries in GitHub Releases post-release
- [ ] Platforms
  - [ ] Steam?
