### ISSUE TITLE
Improve and design themes

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#62]
### Description
- Improve the aesthetics and implementation of themes
- Design a handful of themes
- Extend scope of themes to drawing functions for buttons, text boxes, icon modifier functions, etc.

### Tasks
- [x] Design themes
  - [x] Neon (dark, high-contrast)
  - [x] Zo (eggshell / grey / bone color)
  - [x] Improve current themes
    - [x] Default, minimalist, bunkering
- [x] ~~Dynamic text color (light or dark) based on color rendered below~~
- [x] ~~Add drawing functions to theme~~
  - [ ] button (selection, highlight, base)
  - [ ] textbox
  - [ ] scroll bar
  - [ ] icon modifier functions
  - [ ] icon highlights
