### ISSUE TITLE
Implement automation scripts

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#74]
### Description
Implement automation scripts

### Co-dependents
- #73 

### Tasks
- [x] Validation: contract demands scripts with signature `()` (no params, void return)
  - [x] Status update that mirrors preview scripts in case of failure
- [x] Icon
  - [x] Draw - robot face and script sub-icon
  - [x] Link in Icon Codes
  - [x] Tool tip text: "Run an automation script"
  - [x] Shortcut: `Ctrl +Shift + Q`
  - [x] Add to project info page + blurb
