### ISSUE TITLE
Extend outlining to take an `int[]` as a side mask instead of a `boolean[]`

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#76]
### Description
Extend outlining to take an `int[]` as a side mask instead of a `boolean[]`. A value of `0` represents no outline on a particular edge/corner. A negative value `-v` represents an interior outline of `v` pixels, while a positive value `v` represents an exterior outline of `v` pixels.

### Co-Dependents
- #73 

### Tasks
- [x] Change `Outliner` class implementation
- [x] Redesign and extend `Outline dialog menu`
- [x] Redesign relevant property access in `DialogVals`
- [x] Extend scripting API with following expressions
  - [x] `$outline(int[]{} selection, int[] side_mask) -> int[]{}`
  - [x] `$single_outline(int[]{} selection, int border_px) -> int[]{}`
  - [x] `$double_outline(int[]{} selection, int border_px) -> int[]{}`
  - [x] `$get_side_mask() -> int[]`
  - [x] `$set_side_mask(int[] side_mask);`
