### ISSUE TITLE
Add flatten project action to layer menu

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#77]
### Description
Add a "flatten project" action to the layer menu. This should drop any existing selection to its layer and return an updated project state with a single layer "Flattened" that contains the result of the `ProjectState.draw(false, false, frameIndex)` call for each frame of the animation iff the project contains multiple layers.

### Co-Dependents
- #73 

### Tasks
- [ ] Implement behaviour in a new function `flatten()` in `SEContext`
- [ ] Implement a new layer precondition `canFlatten()` in `ProjectState`
- [ ] Add button to layer menu to the right of "merge with layer below"
  - [ ] Draw icon
  - [ ] Link in `IconCodes`
  - [ ] Add tooltip
  - [ ] Add menu blurb
- [ ] Bind to shortcut **[ Ctrl + M ]**
- [ ] Extend scripting API with the statement `$flatten(project);`

**Comment by jbunke** [comment]
`canRemoveLayer()` is an adequate precondition to represent `flatten()`
