### ISSUE TITLE
Extend scripting API for color actions

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#87]
### Description
Extend the scripting API for color actions

### Tasks
* Color functions
  * [x] `P.palettize(palette pal, int scope, bool include_disabled);`
  * [x] `P.extract_to_pal(palette pal, int scope, bool include_disabled);`
  * [x] `P.hsv_shift(int scope, bool include_disabled, int h_shift, float s_shift, float v_shift);`
  * [x] `P.color_script(int scope, bool include_disabled, string script_path);`
* [x] Complete accompanying documentation
