### ISSUE TITLE
Add a shape tool

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#92]
### Description
Add a shape tool (analogous to the line tool) that draws ellipses and rectangles.

### Tasks
- [x] Draw sprite
- [x] Define tool behaviour in `ShapeTool` class
- [x] Link behaviour to hotkey **[ R ]**
- [x] Write tooltip
- [x] Write blurb
- [x] Link to "Tools" info page in `DialogAssembly`
- [x] Link to tool button in `MenuAssembly`
- [x] Design tool option bar that inherits breadth from `ToolWithBreadth` and also includes dropdown for shape selection
