### ISSUE TITLE
Add frame properties with frame duration

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#96]
### Description
Add frame properties to each frame.

### Properties
- Duration: the duration of a frame relative to a standard frame - ranges from 0.1x to 20x

### Tasks
- [x] Increment native file standard (STIP to 1.2)
- [x] Add serialize and deserialize functions to `ParserSerializer`
- [x] Add to all frame manipulation behaviours (add frame, move frame, remove frame, dupe frame, etc.)
- [x] Apply timings to animation exports (GIF and MP4; may require AnimWriter refactor)
- [x] Extend API
  - [x] `p.get_frame_duration(int frame_index) -> float`
  - [x] `p.set_frame_duration(int frame_index, float frame_duration);`
  - [x] `p.get_frame_durations() -> float[]`
