### ISSUE TITLE
Add script brush tool

### ISSUE THREAD

**Issue by jbunke** [jbunke/stipple-effect#98]
### Description
Add a script brush tool that applies a color script transformation to pixels it paints over.

### Tasks
- [x] Shortcut **[ Q ]**
- [x] Add to `Tool.getAll()`
- [x] `class ScriptBrush`
  - [x] Extends `ToolThatDraws`
  - [x] Implement behaviour
  - [x] Utilize the color script in `DialogVals`
  - [x] Add upload button to the tool options bar
- [x] Add special cursor if there is no valid script
- [x] Draw icon
- [x] Blurb
- [x] Tooltip
